name: Python application test with Github Actions

on: [push]

variables:
  # Docker image details
  imageName: 'predictPreg'
  imageTag: 'latest'

  # Azure Container Registry details
  acrName: 'finaldata'
  acrLoginServer: 'myRegistry.azurecr.io'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirments.txt
        
